# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  host: localhost
  username: root
  password: root
  database: testapp
 

production:
  <<: *default
  host: localhost
  username: root
  password: root
  database: testapp
